name: SlapHomebrew
main: me.naithantu.SlapHomebrew.SlapHomebrew
depend: [Vault, PermissionsEx]
author: naithantu
version: 2.7.1
description: SlapHomebrew homemade plugin.
commands:
  vip:
    description: Same as vipitem.
    usage: /vip
  minecart:
    description: Spawns you inside a moving minecart.
  boat:
    description: Spawns you inside a boat.
  te:
    description: Tps you to the specified player.
  tpblock:
    description: Adds you to a tp block list.  
    aliases: [teblock]
  tpallow:
    description: Add certain players to a whitelist so they can still tp to you when you are blocking teleports.
    aliases: [teallow]
  slap:
    description: Contains all SlapHomebrew management commands and a couple fun commands. 
    aliases: [slaphomebrew]
  backdeath:
    description: Returns you to your death point.
  warppvp:
    description: Warps you to the pvp arena.
  warpcakedefence:
    description: Warps you to cake defence if your inventory is empty.  
    aliases: [warpcake]
  warpsonic:
     description: Warps you to the sonic world to race.
  blockfaq:
    description: Blocks FAQ messages for you.
  cakedefence:
    description: Cake defence commands for staff.
    usage: "Usage:/cakedefence <toggle/startround>"
    aliases: [cake]
  message:
    description: Allows quicker access to default messages.
    usage: "Usage: /message [name] or /message create [name] or /message list or /message show [message]"
  searchregion:
    description: Searches for a worldguard region.
    usage: "Usage: /searchregion [regionname]"
    aliases: [srg, searchrg]
  roll:
    description: Roll a random number to win prizes in the hourly lottery!
  note:
    aliases: [n]
    description: Command to see and change the tone/octave of a note.
    usage: "Usage: /note [octave] [tone]"
  mobcheck:
    description: Searches all mobs nearby online players.
  leavecake:
    description: Teleports you back to spawn and clears your inventory.
  sgm:
    description: Quickly switch between survival and creative gamemodes.
  group:
    description: Check what group a player is in.
    usage: "Usage: /group [playername]"
    aliases: [getgroup]
  potion:
    description: Potion effects commands.
    usage: "Usage: /potion [name] <target(or me/self for self-targeting> <time in s> <power>."
  ride:
    description: Ride other players or entities!
  sonic:
    description: Main command for the sonic racetrack.
  plot:
    description: Multifunctional command for plot-clearing.
  pmark:
    description: Mark a plot to be cleared.
  pcheck:
  ptp:
  pdone:
  bumpdone:
  pay:
    description: Pays another player from your balance
    usage: "Usage: /pay [player] [amount]"
  sparta:
    description: Knock a player back. This is sparta.
    usage: "Usage: /sparta [player]"